name: Build PDI CE

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
     - name: Check Pentaho Repo
       run: |
         echo "=== Root Repo ==="
         curl -I https://repo.pentaho.com/artifactory/pant-mv

         echo "=== Parent POM ==="
         curl -I https://repo.pentaho.com/artifactory/pant-mv/org/pentaho/pentaho-ce-jar-parent-pom

         echo "=== Specific Version ==="
         curl -I https://repo.pentaho.com/artifactory/pant-mv/org/pentaho/pentaho-ce-jar-parent-pom/11.1.0.0-1/

         












         
